services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-openwebui}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  bedrock-gateway:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_PROFILE=${AWS_PROFILE:-default}
      - PORT=8000
      - API_ROUTE_PREFIX=/api/v1
      - DEFAULT_MODEL=${DEFAULT_MODEL:-anthropic.claude-3-sonnet-20240229-v1:0}
      - DEFAULT_EMBEDDING_MODEL=${DEFAULT_EMBEDDING_MODEL:-cohere.embed-multilingual-v3}
      - ENABLE_CROSS_REGION_INFERENCE=${ENABLE_CROSS_REGION_INFERENCE:-false}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ~/.aws:/root/.aws:ro  # Mount AWS config directory as read-only
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/api/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OPENAI_API_BASE_URL=http://bedrock-gateway:8000/api/v1
      - OPENAI_API_KEYS=bedrock
      - DEFAULT_MODEL=${DEFAULT_MODEL:-anthropic.claude-3-sonnet-20240229-v1:0}
      - ENDPOINTS_TYPE=openai
      - HOST=0.0.0.0
      - PORT=3000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-openwebui}
    ports:
      - "3000:3000"
    depends_on:
      bedrock-gateway:
        condition: service_healthy
      postgres:
        condition: service_healthy
